[log]
  level = "ERROR"

[providers.docker]
  exposedByDefault = false
  network = "traefik"

[api]
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
  [entryPoints.dashboard]
    address = ":8080"

[certificatesResolvers]
  [certificatesResolvers.default.acme]
    email = "tarhounisouhaieb@gmail.com"
    storage = "acme.json"
    [certificatesResolvers.default.acme.tlsChallenge]
